"""empty message

Revision ID: bd8901e5b4a8
Revises: 5e2f06b001ba
Create Date: 2022-02-16 12:17:15.264897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8901e5b4a8'
down_revision = '5e2f06b001ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('postings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postings', 'updated_at')
    op.drop_column('postings', 'created_at')
    # ### end Alembic commands ###
