"""empty message

Revision ID: 5e2f06b001ba
Revises: d1d455371538
Create Date: 2022-02-16 11:29:11.392332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2f06b001ba'
down_revision = 'd1d455371538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('saved', 'posting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved', 'posting_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('saved', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
